name: Backstage CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: gha-runner-scale-set

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 24

      - name: Install Build Essentials
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Install Yarn
        run: npm install -g yarn

      - name: Build backstage app
        run: |
          yarn install --immutable
          yarn tsc
          yarn build:backend

      - name: Build backstage docker image
        run: |
          docker image build . -f packages/backend/Dockerfile --tag backstage

      - name: Authenticate and Push from DinD
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_PAT }}
        run: |
          # 1. Authenticate the DinD daemon to Docker Hub
          echo "$DOCKER_TOKEN" | docker login --username "$DOCKER_USER" --password-stdin
          
          # 2. Build your image
          docker build -t $DOCKER_USER/my-app:latest .
          
          # 3. Push the image to Docker Hub
          docker push $DOCKER_USER/backstage:latest
          
          # 4. Clean up credentials (Good practice in DinD environments)
          docker logout
